### ISSUE TITLE
fix import path after renaming

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aws-kinesis-channel#19]

**Comment by tzununbekov** [comment]
@sebgoa I'm not sure if I understand this task right - could you point me to the import path that should be fixed?

**Comment by sebgoa** [comment]
this may not be valid anymore

**Comment by sebgoa** [comment]
looks like this was fixed. you just did not close the issue :)

https://github.com/triggermesh/aws-kinesis-channel/commit/2d4203023f1e99327dd519ffabadeec95e1a49e3#diff-6b87ca68eca277f666490ecf430e4d50

**Comment by tzununbekov** [comment]
right, thanks!
